name: testing actions

on:
  pull_request:
    branches: 
      - dev
      - main
  push:
    branches: 
      - dev
      - main

jobs:
  test:
    name: Running Units Tests
    runs-on: ubuntu-latest
    env:
      CONNECTIONSTRING: ${{secrets.CONNECTIONSTRING}}
      TOKEN_SECRET: ${{secrets.TOKEN_SECRET}}
      EMAIL_PASSWORD: ${{secrets.EMAIL_PASSWORD}}

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: npm install
    - name: Test
      run: npm run test
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [test, build]
    steps:
    - name: Wait for Render Deployment
      uses: bounceapp/render-action@0.6.0
      with:
        render-token: ${{ secrets.RENDER_TOKEN }}
        github-token: ${{ secrets.TOKEN }}
        service-id: srv-cgksc9seoogkndl3t3qg
        retries: 20
        wait: 16000
        sleep: 30000







